apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-checker
  namespace: default
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: deploy-checker
              image: jaimehenao8126/opcion5-deploy-script:latest
              envFrom:
                - secretRef:
                    name: slack-webhook-secret
          restartPolicy: OnFailure