argocd_api: "http://argocd-server.argocd.svc.cluster.local/api/v1"
excluded_apps:
  - argocd-monitor
  - cronjob-deploy-checker
  - cronjob-hello-world
  - prometheus
  - grafana
max_sync_attempts: 3
