apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-monitor-config
  namespace: poc
data:
  ARGOCD_API: "http://argocd-server.argocd.svc.cluster.local/api/v1"  # Agregar /api/v1 al final
  ARGOCD_USERNAME: "admin"  # Nombre de usuario de ArgoCD

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-monitor-sa
  namespace: poc

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-monitor
  namespace: poc
spec:
  schedule: "*/1 * * * *"  # Ejecuta cada minuto
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: argocd-monitor-sa
          containers:
            - name: argocd-monitor
              image: jaimehenao8126/opcion5-deploy-script:3149e47dea8198fe8d8b2073b2352edcc3162fac
              env:
                - name: ARGOCD_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: argocd-monitor-secret
                      key: ARGOCD_TOKEN
                - name: ARGOCD_SERVER
                  value: "localhost:8080"  # Usar localhost:8080
                - name: ARGOCD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: argocd-password-secret
                      key: ARGOCD_PASSWORD
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: slack-webhook-secret
                      key: SLACK_WEBHOOK_URL
              envFrom:
                - configMapRef:
                    name: argocd-monitor-config
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
                requests:
                  memory: "128Mi"
                  cpu: "250m"
          restartPolicy: OnFailure
