apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-checker
  namespace: argocd
spec:
  schedule: "*/5 * * * *"  # Ejecuta cada 5 minutos
  concurrencyPolicy: Forbid  # No permite que se ejecute un nuevo Job si ya hay uno en ejecución
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: deploy-checker
              image: jaimehenao8126/opcion5-deploy-script:latest
              envFrom:
                - secretRef:
                    name: slack-webhook-secret
              env:
                - name: ARGOCD_SERVER
                  value: "localhost:8080"
                - name: ARGOCD_USERNAME
                  value: "admin"
                - name: ARGOCD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: argocd-secret
                      key: password
          restartPolicy: OnFailure