apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-checker
  namespace: argocd
spec:
  schedule: "*/2 * * * *"  # Ejecuta cada 2 minutos
  concurrencyPolicy: Forbid  # No permite que se ejecute un nuevo Job si ya hay uno en ejecución
  successfulJobsHistoryLimit: 1  # Retiene solo 1 Job exitoso
  failedJobsHistoryLimit: 1  # Retiene solo 1 Job fallido
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: deploy-checker
              image: jaimehenao8126/opcion5-deploy-script:7773f8414a41394f0a15972dfcfed1dec6bdbf01
              envFrom:
                - secretRef:
                    name: slack-webhook-secret
              env:
                - name: ARGOCD_SERVER
                  value: "http://192.168.49.2:8080"  # Kubernetes Node IP
                - name: ARGOCD_USERNAME
                  value: "admin"
                - name: ARGOCD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: argocd-secret
                      key: admin.password
          restartPolicy: OnFailure
