apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-checker
  namespace: argocd
spec:
  schedule: "*/2 * * * *"  # Ejecuta cada 5 minutos
  concurrencyPolicy: Forbid  # No permite que se ejecute un nuevo Job si ya hay uno en ejecución
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: deploy-checker
              image: jaimehenao8126/opcion5-deploy-script:7ba4ba0f3bafbec808d15cbc05150250385106cb
              envFrom:
                - secretRef:
                    name: slack-webhook-secret
              env:
                - name: ARGOCD_SERVER
                  value: "localhost:8080"
                - name: ARGOCD_USERNAME
                  value: "admin"
                - name: ARGOCD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: argocd-secret  # Se mantiene el secreto correcto
                      key: admin.password  # Cambiado para usar la clave correcta
          restartPolicy: OnFailure
