apiVersion: batch/v1
kind: CronJob
metadata:
  name: deploy-checker
  namespace: argocd
spec:
  schedule: "*/2 * * * *"  # Ejecuta cada 2 minutos
  concurrencyPolicy: Forbid  # No permite que se ejecute un nuevo Job si ya hay uno en ejecución
  successfulJobsHistoryLimit: 1  # Retiene solo 1 Job exitoso
  failedJobsHistoryLimit: 1  # Retiene solo 1 Job fallido
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: deploy-checker
              image: jaimehenao8126/opcion5-deploy-script:163abd185bd8451e25be18c2db234dfaff9baacb
              envFrom:
                - secretRef:
                    name: slack-webhook-secret
              env:
                - name: ARGOCD_SERVER
                  value: "$(MINIKUBE_IP):8080"  # Use Minikube Node IP
                - name: ARGOCD_USERNAME
                  value: "admin"
                - name: ARGOCD_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: argocd-secret
                      key: admin.password
                - name: ARGOCD_API
                  value: "https://$(MINIKUBE_IP):8080/api/v1"  # Replace with the correct API URL
                - name: ARGOCD_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: argocd-token-secret
                      key: token  # Ensure this secret exists
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: slack-webhook-secret
                      key: SLACK_WEBHOOK_URL
          restartPolicy: OnFailure
          initContainers:
            - name: get-minikube-ip
              image: jaimehenao8126/opcion5-deploy-script:163abd185bd8451e25be18c2db234dfaff9baacb
              command: ["sh", "-c"]
              args:
                - |
                  export MINIKUBE_IP=$(minikube ip) && echo $MINIKUBE_IP > /etc/minikube-ip/env
              volumeMounts:
                - name: minikube-ip
                  mountPath: /etc/minikube-ip
          volumes:
            - name: minikube-ip
              emptyDir: {}
