apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
  namespace: poc
spec:
  project: default
  source:
    repoURL: https://github.com/JaimeHenaoChallange/opcion5-cronjob-python.git
    targetRevision: HEAD
    path: ./app_flask
  destination:
    server: https://kubernetes.default.svc
    namespace: poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true