apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JaimeHenaoChallange/opcion5-cronjob-python.git
    targetRevision: HEAD
    path: monitoreo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ports:
    - port: 8000
  selector:
    matchLabels:
      app: argocd-monitor
