apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: poc
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "cronjob-monitor"
        static_configs:
          - targets: ["localhost:8000"]
