apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: poc
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "cronjob-monitor"
        static_configs:
          - targets: ["cronjob-monitor.poc.svc.cluster.local:8000"]  # Dirección del servicio
