name: Deploy Prometheus and Grafana with Minikube

on:
  push:
    paths:
      - "monitoreo/**"
      - ".github/workflows/prometheus-grafana-deploy.yml"
  workflow_dispatch:

jobs:
  deploy-prometheus-grafana:
    name: Deploy Prometheus and Grafana
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Minikube
      run: |
        echo "Starting Minikube..."
        minikube start --driver=docker

    - name: Set up kubectl for Minikube
      run: |
        echo "Configuring kubectl for Minikube..."
        kubectl config use-context minikube

    - name: Install ArgoCD CRDs
      run: |
        echo "Installing ArgoCD CRDs..."
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Verify kubectl context
      run: |
        kubectl config current-context
        kubectl cluster-info

    - name: Create Namespace for Monitoring
      run: |
        echo "Creating namespace for monitoring..."
        kubectl create namespace poc || echo "Namespace 'poc' already exists"
        kubectl create namespace argocd || echo "Namespace 'argocd' already exists"

    - name: Apply Prometheus and Grafana Configurations from GitHub
      run: |
        echo "Applying manifests from the repository..."
        kubectl apply -f ./monitoreo/prometheus-configmap.yaml
        kubectl apply -f ./monitoreo/prometheus-deployment.yaml
        kubectl apply -f ./monitoreo/grafana-configmap.yaml
        kubectl apply -f ./monitoreo/grafana-deployment.yaml

    - name: Apply ArgoCD Applications from GitHub
      run: |
        kubectl apply -f ./monitoreo/prometheus-application.yaml
        kubectl apply -f ./monitoreo/grafana-application.yaml

    - name: Verify Prometheus and Grafana in ArgoCD
      run: |
        kubectl get applications -n argocd
