name: Deploy Prometheus and Grafana with ArgoCD

on:
  push:
    paths:
      - "monitoreo/**"
      - ".github/workflows/prometheus-grafana-deploy.yml"
  workflow_dispatch:

jobs:
  deploy-prometheus-grafana:
    name: Deploy Prometheus and Grafana
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up kubectl
      run: |
        echo "Setting up kubectl..."
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Apply Prometheus and Grafana Configurations
      run: |
        kubectl apply -f monitoreo/prometheus-configmap.yaml
        kubectl apply -f monitoreo/prometheus-deployment.yaml
        kubectl apply -f monitoreo/grafana-configmap.yaml
        kubectl apply -f monitoreo/grafana-deployment.yaml

    - name: Apply ArgoCD Applications
      run: |
        kubectl apply -f monitoreo/prometheus-application.yaml
        kubectl apply -f monitoreo/grafana-application.yaml

    - name: Verify Prometheus and Grafana in ArgoCD
      run: |
        kubectl get applications -n argocd
